---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: ssh://git@github.com/leehanel/homeops.git
        revision: HEAD
        directories:
        - path: cluster/t/core/*
  template:
    metadata:
      name: 'core-{{path.path}}'
      namespace: argocd
    spec:
      source:
        repoURL: ssh://git@github.com/leehanel/homeops.git
        targetRevision: HEAD
        path: '{{path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated: 
          prune: true
        syncOptions: []
