annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated code-server image tag to v4.10.0
    - kind: changed
      description: Updated netshoot image tag to v0.9
    - kind: fixed
      description: Pod annotations were not indented enough when controller type was cronjob
apiVersion: v2
description: Function library for Helm charts
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
keywords:
- common
- library
kubeVersion: '>=1.22.0-0'
maintainers:
- email: me@bjw-s.dev
  name: bjw-s
name: common
type: library
version: 1.3.2
