---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- wildcard.yaml
namespace: nginx
helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  namespace: nginx
  version: 4.11.3
  valuesFile: nginx.yaml
  
