---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  name: sleep-1
  namespace: dev
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ubuntu
        name: sleep
        command: ["sleep", "30"]
      restartPolicy: Never
