---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secrets
    creationPolicy: Owner
    #template:
      #engineVersion: v2
      #data:
        #pve: |
          #{{ .password }}
  #dataFrom:
    #- extract:
        ##key: pve
