---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: GF_DATABASE_TYPE
      remoteRef:
        key: grafana-secrets
        property: type
    - secretKey: GF_DATABASE_HOSTNAME
      remoteRef:
        key: grafana-secrets
        property: hostname
    - secretKey: GF_DATABASE_PASSWORD
      remoteRef:
        key: grafana-secrets
        property: credential
    - secretKey: GF_DATABASE_USERNAME
      remoteRef:
        key: grafana-secrets
        property: username
