---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_DATABASE_TYPE: postgresql
        GF_DATABASE_PASSWORD: {{ .credential }}
        GF_DATABASE_USERNAME: {{ .username }}
        GF_DATABASE_HOSTNAME: {{ .hostname }}
