---
namespace: monitoring
helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  namespace: monitoring
  version: "45.29.0"
  valuesFile: prom.values
- name: grafana
  repo: https://grafana.github.io/helm-charts
  version: 6.56.1
  releaseName: grafana
  valuesFile: grafana.values
- name: prometheus-blackbox-exporter
  releaseName: blackbox-exporter
  repo: https://prometheus-community.github.io/helm-charts
  namespace: monitoring
  version: "7.7.0"
  valuesFile: blackbox.values
- name: app-template
  namespace: monitoring
  version: 1.3.2
  repo: https://bjw-s.github.io/helm-charts/
  releaseName: pve-expoter
  valuesFile: pve-exporter.values
