---
namespace: monitoring
helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  namespace: monitoring
  version: "45.9.1"
  valuesFile: prom.values
  
