---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pve-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: |
          {{ .password }}
  dataFrom:
    - extract:
        key: password
