---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: app-o-app0
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/leehanel/homeops.git'
    path: cluster/apps/app/app0
    targetRevision: v1.0.9
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
