
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: app2
  namespace: dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/leehanel/homeops.git'
    path: cluster/apps/app/app2
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
