---
apiVersion: v1
kind: Service
metadata:
  name: allsky-public
  namespace: home
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: allsky-public
  namespace: home
subsets:
  - addresses:
    - ip: 192.168.0.120
    ports:
    - port: 8089
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allsky-public
  namespace: home
spec:
  ingressClassName: ingress-internal
  rules:
  - host: allsky.i.ctr.farm
    http:
      paths:
      - backend:
          service:
            name: allsky-public
            port:
              number: 8080
        path: /
        pathType: Prefix
