---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: home
  name: frigate-config
data:
  config.yaml: |
    mqtt:
      host: 192.168.1.120
      topic_prefix: frigate
      user: "{FRIGATE_MQTT_USERNAME}"
      password: "{FRIGATE_MQTT_PASSWORD}"
    detectors:
      coral_pci:
        type: edgetpu
        device: pci
    cameras:
      lillie:
        ffmpeg:
          inputs:
            - path: rtsp://192.168.3.17:8554/video3_unicast
              roles:
                - detect
                - rtmp
                - clips
                - record
        width: 1920
        height: 1080
        best_image_timeout: 60
        fps: 5
        mqtt:
          enabled: false
        record:
          enabled: True
          retain_days: 30
      goats:
        ffmpeg:
          inputs:
            - path: rtsp://road:road@192.168.3.25/live
              roles:
                - detect
                - rtmp
                - clips
                - record
        width: 1920
        height: 1080
        best_image_timeout: 60
        fps: 5
        mqtt:
          enabled: false
        record:
          enabled: True
          retain_days: 30
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 2
          mode: active_objects
    objects:
      track: ["person"]
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.7
