---
namespace: home
resources: 
- esphome-pvc.yaml
helmCharts:
- name: app-template
  releaseName: esphome
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.1.3
  valuesFile: esphome.values
  
- name: app-template
  releaseName: zigbee2mqtt-shop
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.1.3
  valuesFile: zigbee2mqtt-shop.values
  
- name: app-template
  releaseName: mosquitto.values
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.1.3
  valuesFile: mosquitto.values
  
