---
namespace: home
resources: 
- allsky-public.yaml
- esphome-pvc.yaml
- mosquitto-pvc.yaml
- mosquitto-secrets.yaml
- zigbee2mqtt-shop-pvc.yaml
- zigbee2mqtt-shop-secrets.yaml
helmCharts:
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.1.3
  releaseName: esphome
  valuesFile: esphome.values
  
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.1.3
  releaseName: zigbee2mqtt-shop
  valuesFile: zigbee2mqtt-shop.values
  
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.2.0
  releaseName: mosquitto
  valuesFile: mosquitto.values
  
