---
namespace: home
resources: 
- allsky-public.yaml
- esphome-pvc.yaml
- frigate-pvc.yaml
- mosquitto-pvc.yaml
- mosquitto-secrets.yaml
- zigbee2mqtt-pvc.yaml
- zigbee2mqtt-shop-secrets.yaml
helmCharts:
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.1.3
  releaseName: changedetection
  valuesFile: changedetection.values
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.1.3
  releaseName: esphome
  valuesFile: esphome.values
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.3.2
  releaseName: zigbee2mqtt-house
  valuesFile: zigbee2mqtt-house.values

- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: home
  version: 1.3.2
  releaseName: zigbee2mqtt-shop
  valuesFile: zigbee2mqtt-shop.values

- name: app-template
  namespace: home
  version: 1.3.2
  repo: https://bjw-s.github.io/helm-charts/
  releaseName: frigate
  valuesFile: frigate.values
