---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mosquitto-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mosquitto_pwd: |
          {{ .mosquitto_zigbee2mqtt_username }}:{{ .mosquitto_zigbee2mqtt_password }}
  dataFrom:
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mosquitto_$1"
