---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secrets
    creationPolicy: Owner
  data:
    - secretKey: mqtt_user
      remoteRef:
        key: mosquitto
        property: zigbee2mqtt_username
    - secretKey: mqtt_password
      remoteRef:
        key: mosquitto
        property: zigbee2mqtt_password
