---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
namespace: external-dns
helmCharts:
  - name: external-dns
    releaseName: external-dns
    repo:  https://kubernetes-sigs.github.io/external-dns/
    version: 1.15.0
    valuesFile: external-dns.yaml
