---
namespace: kube-system
resources:
- https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.16.1
helmCharts:
#- name: kube-monkey
  #version: 1.5.2
  #repo: https://asobti.github.io/kube-monkey/charts/repo
  #valuesFile: kubemonkey.values
  #namespace: kube-system
#- name: node-feature-discovery
  #version:  0.16.1
  #repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  #namespace: kube-system
  #valuesFile: nfd.values
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  namespace: kube-system
  version: 1.2.1
  releaseName: intel-gpu-plugin
  valuesFile: intel-gpu-plugin.values
#- name: volsync
  #repo: https://backube.github.io/helm-charts/
  #version: 0.5.0
  #namespace: volsync-system
#- name: snapshot-controller
  #repo: https://piraeus.io/helm-charts/
  #version: 1.7.2
  #namespace: kube-system
  #valuesFile: snapshot-controller.yaml
