---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync-system
helmCharts:
  - name: snapshot-controller
    includeCRDs: true
    namespace: volsync-system
    repo: https://piraeus.io/helm-charts/
    releaseName: snapshot-controller
    version: 3.0.6
    valuesFile: snapshot-controller.yaml
