---
namespace: rook-ceph
resources:
- namespace.yaml
helmCharts:
- name: rook-ceph
  releaseName:  rook-ceph
  repo: https://charts.rook.io/release
  namespace: rook-ceph
  version:  v1.10.6
  valuesFile: operator.yaml
- name: rook-ceph-cluster
  releaseName:  rook-cluster
  repo: https://charts.rook.io/release
  namespace: rook-ceph
  version:  v1.10.6
  valuesFile: cluster.yaml
