---
#namespace: rook-ceph
resources:
- namespace.yaml
helmCharts:
- name: rook-ceph
  releaseName:  rook-ceph
  repo: https://charts.rook.io/release
  namespace: rook-ceph
  version:  v1.14.0
  valuesFile: operator.yaml
- name: rook-ceph-cluster
  releaseName:  rook-ceph
  repo: https://charts.rook.io/release
  namespace: rook-ceph-external
  version:  v1.13.1
  valuesFile: external-cluster.yaml
- name: rook-ceph-cluster
  releaseName:  rook-ceph
  repo: https://charts.rook.io/release
  namespace: rook-ceph
  version:  v1.13.4
  valuesFile: cluster.yaml
patches:
- target:
    kind: CephFilesystem
    name: ceph-filesystem
    namespace: rook-ceph
  patch: |-
    - op: replace
      path: /spec/metadataServer/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/metadataServer/resources/requests/memory
      value: 64Mi
