---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
            - server: 'https://kubernetes.default.svc'
              name: in-cluster
        - git:
            repoURL: 'https://github.com/leehanel/homeops.git'
            revision: HEAD
            directories:
            - path: cluster/core/*
  template:
    metadata:
      name: '{{path[1]}}-{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/leehanel/homeops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: argocd
      syncPolicy:
        automated: 
          prune: true
        syncOptions: []
