apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: dev
spec:
  selector:
    matchLabels:
      app: helloworld
      instance: app2
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: helloworld
        instance: app2
    spec:
      containers:
      - name: helloworld
        image: wordpress:latest
        ports:
        - containerPort: 8080
