---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tailscale-secret.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
- name: tailscale-operator
  releaseName: tailscale-operator
  namespace: networking
  valuesFile: tailscale.yaml
  version: 0.1.0
