---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-key
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: |
          {{ .credential }}
  dataFrom:
    - extract:
        key: tailscaleoperator
