---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-key
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: operator-oauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      stringData:
        client_id: |
          {{ .username }}
        client_secret: |
          {{ .credential }}
  dataFrom:
    - extract:
        key: tailscaleoperator
