---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invidious
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        INVIDIOUS_CONFIG: |
          database_url: postgres://{{ .username }}:{{ .password }}@postgres.i.ctr.farm:5432/invidious
          check_tables: true
          port: 3000
          channel_threads: 2
          feed_threads: 2
          domain: invidious.i.ctr.farm
          https_only: false
          hmac_key: {{ .HMAC_KEY }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: invidious
        INIT_POSTGRES_HOST: postgres.i.ctr.farm
        INIT_POSTGRES_USER: "{{ .username }}"
        INIT_POSTGRES_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: invidious
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  wallabag
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wallabag
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        postgres: postgres://{{ .username }}:{{ .password }}@{{  .server }}:{{ .port }}/{{ .database }}
  dataFrom:
    - extract:
        key: wallabag

