---
namespace: media
resources:
-  jellyfin-pvc.yaml
helmCharts:
- name: app-template
  version: 1.1.3
  repo: https://bjw-s.github.io/helm-charts/
  namespace: media
  releaseName: jellyfin
  valuesFile: jellyfin.values
  
