---
namespace: media
resources:
- handbrake-pvc.yaml
- jellyfin-pvc.yaml
- external-secret.yaml
helmCharts:
- name: app-template
  version: 1.5.1
  repo: https://bjw-s.github.io/helm-charts/
  namespace: media
  releaseName: jellyfin
  valuesFile: jellyfin.values
  
- name: app-template
  version: 1.5.1
  repo: https://bjw-s.github.io/helm-charts/
  namespace: media
  releaseName: invidious-server
  valuesFile: invidious.values

- name: app-template
  version: 1.5.1
  repo: https://bjw-s.github.io/helm-charts/
  namespace: media
  releaseName: handbrake
  valuesFile: handbrake.values
