---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-linkwarden
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-blockpool
