apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: dev
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 2
  containers:
      - name: hello-world
        image: helloworld
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
