# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:Pjdb/VBSkuDtyJ3eLLyNverdW6rgq2ELYWYoDxE2tATKQS90NA==,iv:W1ZUAfYWJkM9UsiL/OsqiB/Qfscs0uYssOkiiokKj8A=,tag:QXYdJvbjrNZxMoFc2wSZYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-19T00:49:18Z"
    mac: ENC[AES256_GCM,data:YcU4ieI+O6ikOVgYsykJT7OE/xTOBv1qjMuBVS+93X3TgQuW0orhTBALsbnva3+FlJ1T/2zDalsnOIJ85OndHFiE5oDFhS1DyMy6PDJFpsmwYIHS7AHf2zhf7dswYhplNC3Nt0GQ51Wv6rTFA4IGm3fz/ddU6eOtPGNWG48txm8=,iv:mhDQsnPfnbv/L6GpYLdyRCn3CE+HAjxAKnrqKZo1gBk=,tag:a3ew3wrAXC8AEe9xckrM/A==,type:str]
    pgp:
        - created_at: "2022-11-19T00:49:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/BOBhDCSTdaAQ//QBpKxBtsULq0LwLO4Fn45XdBDV7t5WYwU3TVFl1PCo9X
            rCkYPE71wJuGbPSBOQyvNpTxaWYl2ggJSg4Yt4usVgl8ivlLhRfuwcbjNiJODCdz
            u+0v5C1neDySzJQ6NRGqzLffTuOkKMN10nOU78xEQTIqkoA6k1ZTRNI31QJ8Oq+6
            h1RIiVUgJ8nxPpUbaKfPQA3gHg/OXGUJEP29noqiJjzR5OKR1m18ETWO/k85Zf7A
            GPArOGw5/ZjPoiYCwpN8txbXXKNmNnap6o1xji2l/AuXONeAlNcp9VPXR6CSbM51
            N/qlIYH1GU5nUD2krxs99NZCXdI0qz76Ic76FB7ni5N6+hJa4Piu5e3L4124Ga6y
            SB753w8qGx0Y3biC5XeL7opttLLSFkfmKcUes1xoapg7aZKsVnV62lltvFDs0FiM
            yvtlgmFkdYi6qFl6Y/5SQ/0jW95I9TT1jiAt/SJI0zlya4d03fqOWKaaVztodTyt
            MGMkmcn5NHRJOHxLuoJTIjRdCofRe3qyB1lJgwYXKweg1Y8TOUCLa978zvd965ZN
            zRcASOMVhJ6VvdkH+oijxmcG12M4bwSHokiZ/FLh7iXCklR2Ka7ksLChT2UsR/m7
            XdM+RDkm8Rcj6yJLQpJO//8p3AX/N2UkYt1P9TL3NN64qTUKzUzsQu/5HGkCUHHS
            UQHRdGUJQEizs+2l6ppQkJbCxb6YSk8plDhGdPOrleoQVkKmvFUnQl80aPgO7b4j
            UtUL1b4mX/MM/nwwWIGyLvTma7zs1bltO+NWFhwzAnmRZw==
            =OVqv
            -----END PGP MESSAGE-----
          fp: 7E6B7AF994D693BDA92B0BF3EB5345BF800EAF06
        - created_at: "2022-11-19T00:49:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAzH/5dH83P1hARAAiwB4DTJN6A/zzFnwwGOWrJF9rkuWwEap+W0eCZOyh/DY
            hWQ8n3Z9fMcdLdPcApUQM80BPm3KloWjb9/h5UB60ClF8cmda5rjgv5gL5DkDUVa
            XSNIKr8RO2jbthPl+/nuQkXKFUYReFnF8kBAXSpAu6r2s6cjJkCwjBdLgXG1XCrJ
            PWDzOMwXURmxwWtt6LlL7JESvBIMV9lmaGTMyS0osFeCpvLWdvjy3xML9eJCz7oZ
            +79BWvaHyP3pBpj6cNhoBWnm+OHQd7GEkNrOp6ViZsYn50fXie552kVBuUFnM3kv
            El/wnGxfVkYFjHF19qHvHVx/JGfmLWYGKI0XxNiNm/fu/b06E6+Fp6X9hpbrn7F7
            la0ayFFUbgRHHPc3amTxxNttORv5uPIAQdn+V94nfLoAX9MwIshYbYgefoELs7DC
            ebyNPePVjC3JJIOfVOSJPAL1FECas8Mmv/jDlOngIgwaSrDh5fmUSP/6ynlDsDa4
            hb7U0DcdMB+jVbCJGvUrByQczrmAqUc1YfopRnnjChsZVhsdSiMho6++4ejICbp9
            sWvCw7WAKBiD+LIBSLAvvX6+e9QZQiVgzLvBFyU4m5CgWygoHyyhXw3ZcSAm0JIo
            x51cXkaOM5eAzBOak2kN6HC7mb8DieG/2fJBNk2o8FOWNK+oG4pya3aVHvInV4nS
            UQH25ckgRj1B2lthmojebjdCmmZJo/ZOnJYc4Z4y0sMwI9NKBOHAqNPqszQx03yb
            T7iFCEGkPw5Zg8AAJ7XRDwGZxwL6AXuzPkv7Xdv3vEj6nw==
            =EPg7
            -----END PGP MESSAGE-----
          fp: 404635DC2665EDDDF6796D304A5D71921947843D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
