---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "lee.hanel@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "lee.hanel@gmail.com"
            apiKeySecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsNames:
          - i.ctr.farm
          - '*.i.ctr.farm'
          - internal.ctr.farm
          - '*.internal.ctr.farm'
