---
namespace: monitoring
resources:
- grafana-secrets.yaml
#- proxmox-secrets.yaml
helmCharts:
- name: kube-prometheus-stack
  releaseName: prom
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  version: "66.2.1"
  valuesFile: prom.values
- name: grafana
  repo: https://grafana.github.io/helm-charts
  version: 8.3.1
  releaseName: grafana
  valuesFile: grafana.values
- name: prometheus-blackbox-exporter
  releaseName: blackbox-exporter
  repo: https://prometheus-community.github.io/helm-charts
  version: "7.7.0"
  valuesFile: blackbox.values
- name: app-template
  version: 1.3.2
  repo: https://bjw-s.github.io/helm-charts/
  releaseName: pve-expoter
  valuesFile: pve-exporter.values
